version: 1
update_configs:
  # Creates weekly Pull Requests with dependency updates and auto-merges devDependency updates.
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    target_branch: "master"
    allowed_updates:
      - match:
          dependency_type: "production"
          update_type: "all"
      - match:
          dependency_type: "development"
          update_type: "all"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "all"
    version_requirement_updates: "increase_versions"
